# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'channel_choose.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Channel_choose(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 350)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_nameset = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.label_nameset.setFont(font)
        self.label_nameset.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nameset.setObjectName("label_nameset")
        self.gridLayout.addWidget(self.label_nameset, 0, 0, 1, 1)
        self.lineEdit_nameset = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_nameset.sizePolicy().hasHeightForWidth())
        self.lineEdit_nameset.setSizePolicy(sizePolicy)
        self.lineEdit_nameset.setObjectName("lineEdit_nameset")
        self.gridLayout.addWidget(self.lineEdit_nameset, 0, 1, 1, 2)
        self.label_channel_choose = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.label_channel_choose.setFont(font)
        self.label_channel_choose.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_channel_choose.setObjectName("label_channel_choose")
        self.gridLayout.addWidget(self.label_channel_choose, 1, 0, 1, 1)
        self.scrollArea_channel_choose = QtWidgets.QScrollArea(Dialog)
        self.scrollArea_channel_choose.setWidgetResizable(True)
        self.scrollArea_channel_choose.setObjectName("scrollArea_channel_choose")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 480, 248))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_channel_choose.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea_channel_choose, 2, 0, 1, 3)
        self.label_sampling_rate = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.label_sampling_rate.setFont(font)
        self.label_sampling_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sampling_rate.setObjectName("label_sampling_rate")
        self.gridLayout.addWidget(self.label_sampling_rate, 3, 0, 1, 1)
        self.lineEdit_sampling_rate = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_sampling_rate.sizePolicy().hasHeightForWidth())
        self.lineEdit_sampling_rate.setSizePolicy(sizePolicy)
        self.lineEdit_sampling_rate.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_sampling_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_sampling_rate.setObjectName("lineEdit_sampling_rate")
        self.gridLayout.addWidget(self.lineEdit_sampling_rate, 3, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(11)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 2, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Channel Choose"))
        self.label_nameset.setText(_translate("Dialog", "Dataset name"))
        self.label_channel_choose.setText(_translate("Dialog", "Channel choose"))
        self.label_sampling_rate.setText(_translate("Dialog", "Data sampling rate (Hz)"))
        self.lineEdit_sampling_rate.setText(_translate("Dialog", "1024"))
